name: Build APK
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cari dan Rakit APK
        run: |
          # Perintah ini akan mencari di mana file gradlew berada otomatis
          GRADLEW_PATH=$(find . -name gradlew | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "Aduh beb, file gradlew gak ketemu di mana-mana!"
            exit 1
          fi
          DIR_PATH=$(dirname "$GRADLEW_PATH")
          cd "$DIR_PATH"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload Hasil
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/build/outputs/apk/debug/*.apk"
